### ISSUE TITLE
Problem with util_file.fix_slashes and UNC paths

### ISSUE THREAD

**Issue by YKdvd** [louisVottero/vtool#24]
The routine [vtool.util_file.fix_slashes()](https://github.com/louisVottero/vtool/blob/59f3d7a00ce5aeedfa2841fff032c5c87812dade/python/vtool/util_file.py#L2284) attempts to convert Windows "\\" path separator backslashes to the forward slash "/", which will still work on Windows.  But it then converts doubled slashes ("//") to a single slash.  This is problematic for UNC paths on windows, which start with a doubled separator ("\\\\hostname\\sharename\\dirname", etc).  Given that example, it produces "/hostname/sharename/dirname", which is no longer valid on Windows.  We came across the problem while trying to use a shared network copy the vtool package on a networked drive (UNC path) in our studio pipeline.

```python
    if not directory.find('https://') > -1:
        directory = directory.replace('//', '/')
````

I'm not sure what the intent of removing the doubled slashes was.  Posix filesystems are designed to treat multiple slashes to a single slash and should have no problem with them, and Windows appears to handle doubled slashes internally as well, while removing the initial doubled slash for a UNC path obviously breaks it.

We're going to try just disabling that bit of fix_slashes, and if I get a chance I'll submit a pull request with that patch.

**Comment by louisVottero** [comment]
I've created this pull request if you'd like to check it.  I can add you to the vtool project as a developer if you would like. 
https://github.com/louisVottero/vtool/pull/25

**Comment by louisVottero** [comment]
The fix is merged into main. Closing this issue.
