### ISSUE TITLE
userSetup.py can get accidentally run if "python" dir put on PYTHONPATH

### ISSUE THREAD

**Issue by YKdvd** [louisVottero/vtool#27]
There is a userSetup.py file in the "python" folder, sort of a template for the user copy, modify and put in one of the directories Maya looks in - it isn't intended to be run as is.  But if you set up vtool by putting the "python" folder on PYTHONPATH (as one might with a central copy in a studio setting), then Maya will run this one - it runs userSetup.py from all directories on PYTHONPATH

I've create a pull request which moves this file into a separate "install" folder - the name and location doesn't matter, as long as this userSetup isn't in a place that will be put on PYTHONPATH.

Pull request - https://github.com/louisVottero/vtool/pull/26

**Comment by louisVottero** [comment]
Thanks! This helps alot.  I will move it out of the python folder

**Comment by louisVottero** [comment]
Approved and merged. Thanks again
