### ISSUE TITLE
ast.NamedConstant deprecated

### ISSUE THREAD

**Issue by YKdvd** [louisVottero/vtool#30]
There's a pull request (https://github.com/louisVottero/vtool/pull/29) to fix a typo in a check for Python 3 in util_file.

The check was being done around some use of the stdlib "ast" parsing module.  There's a use of the ast.NameConstant, whichI notice is deprecated in Python 3.8, and will eventually be removed.  At some point you may want to replace that with ast.Constant, which I think is used for all cases now, but I didn't dig in to make sure.  Looks like they are still around in early 3.11 releases, so no rush... :)

**Comment by louisVottero** [comment]
Thanks! 
Wanted to try it out. This should be fixed in this pull request
https://github.com/louisVottero/vtool/pull/32
